wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: huggingface
    huggingface_version: 4.46.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.14
    start_time: 1754053374
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      4: 3.10.14
      5: 0.12.18
      6: 4.46.1
      8:
      - 5
alpha:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: MNIST
fid_batch_size:
  desc: null
  value: 50
fid_num_samples:
  desc: null
  value: 500
hidden_features:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0001
max_epochs:
  desc: null
  value: 10
model_type:
  desc: null
  value: JEM
use_gpu:
  desc: null
  value: true
