hidden_features: 32
num_classes: 10
lr: 0.0001
beta1: 0.0
alpha: 0.1
sample_size: 64
max_buffer_len: 8192
mcmc_steps: 60
mcmc_step_size: 10.0
scheduler_step_size: 1
scheduler_gamma: 0.97
fid_num_samples: 500
fid_batch_size: 50
